# Basic
title: 胖哥的自留地
subtitle: 一个不爱吹牛逼的打工仔
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">下载这个主题</a>
description: 自豪的使用Github Page作为博客
creator: <a href="http://www.ny9s.com">@奶油九叔</a>

url: "http://www.ny9s.com"

permalink: /:year/:month/:title/

# Format
highlighter: pygments

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 造访博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 项目描述, url: 'http://www.ny9s.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

highlighter: pygments
markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]
kramdown:
  input:         GFM
  auto_ids:      true
  auto_id_prefix:'id-'


# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: kukisama
    github: kukisama
    #twitter: pangzi
    #gplus: xxxxx
    #mail: pangzi@p.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
